html.tag.anchor=a
html.tag.abbreviation=abbr
html.tag.address=address
html.tag.area=area
html.tag.article=article
html.tag.aside=aside
html.tag.audio=audio
html.tag.bold=b
html.tag.base=base
html.tag.bdi=bdi
html.tag.bdo=bdo
html.tag.blockquote=blockquote
html.tag.body=body
html.tag.break=br
html.tag.button=button
html.tag.canvas=canvas
html.tag.caption=caption
html.tag.cite=cite
html.tag.code=code
html.tag.col=col
html.tag.colgroup=colgroup
html.tag.data=data
html.tag.datalist=datalist
html.tag.definition=dd
html.tag.deleted=del
html.tag.details=details
html.tag.definitionterm=dfn
html.tag.dialog=dialog
html.tag.div=div
html.tag.descriptionlist=dl
html.tag.emphasis=em
html.tag.embed=embed
html.tag.fieldset=fieldset
html.tag.figcaption=figcaption
html.tag.figure=figure
html.tag.footer=footer
html.tag.form=form
html.tag.heading1=h1
html.tag.heading2=h2
html.tag.heading3=h3
html.tag.heading4=h4
html.tag.heading5=h5
html.tag.heading6=h6
html.tag.head=head
html.tag.header=header
html.tag.hr=hr
html.tag.html=html
html.tag.italic=i
html.tag.iframe=iframe
html.tag.image=img
html.tag.input=input
html.tag.ins=ins
html.tag.keyboard=kbd
html.tag.label=label
html.tag.legend=legend
html.tag.listitem=li
html.tag.link=link
html.tag.main=main
html.tag.map=map
html.tag.mark=mark
html.tag.meta=meta
html.tag.meter=meter
html.tag.nav=nav
html.tag.noscript=noscript
html.tag.object=object
html.tag.orderedlist=ol
html.tag.optgroup=optgroup
html.tag.option=option
html.tag.output=output
html.tag.paragraph=p
html.tag.param=param
html.tag.picture=picture
html.tag.preformatted=pre
html.tag.progress=progress
html.tag.quote=q
html.tag.ruby=rb
html.tag.rubytext=rt
html.tag.rubyparentheses=rp
html.tag.strikethrough=s
html.tag.sample=samp
html.tag.script=script
html.tag.section=section
html.tag.select=select
html.tag.small=small
html.tag.source=source
html.tag.span=span
html.tag.strong=strong
html.tag.style=style
html.tag.subscript=sub
html.tag.summary=summary
html.tag.superscript=sup
html.tag.table=table
html.tag.tbody=tbody
html.tag.td=td
html.tag.template=template
html.tag.textarea=textarea
html.tag.tfoot=tfoot
html.tag.th=th
html.tag.thead=thead
html.tag.time=time
html.tag.title=title
html.tag.tr=tr
html.tag.track=track
html.tag.underline=u
html.tag.unorderedlist=ul
html.tag.variable=var
html.tag.video=video
html.tag.wbr=wbr

# Deprecated HTML tags (invalid in HTML5)
html.tag.applet=applet
html.tag.acronym=acronym
html.tag.basefont=basefont
html.tag.big=big
html.tag.center=center
html.tag.dir=dir
html.tag.font=font
html.tag.frame=frame
html.tag.frameset=frameset
html.tag.noframes=noframes
html.tag.strike=strike
html.tag.tt=tt
html.tag.isindex=isindex
html.tag.listing=listing
html.tag.xmp=xmp
html.tag.plaintext=plaintext
html.tag.bgsound=bgsound
html.tag.marquee=marquee
html.tag.multicol=multicol
html.tag.nextid=nextid
html.tag.spacer=spacer
html.tag.noembed=noembed
html.tag.nolayer=nolayer
html.tag.layer=layer
html.tag.ilayer=ilayer